#:kivy 2.0.0
<LoginScreen>:
    GridLayout:
        cols:1
        size: root.width, root.height
        GridLayout:
            cols:2
            Label:
                id:usernamelabel
                text:"User Name"
            TextInput:
                multiline:False
            Label:
                id:emaillabel
                text:"Email"
            TextInput:
                multiline:False
        Button:
            text:"Generate Password"
    
